myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from myblog.views import *
from mysecondsite.urls import *

app_name ="myblog"

urlpatterns = [
    path("",view_index,name='index'),
    path("about",view_about,name='about'),
    path("test",view_test,name='test'),
]

mysecondsite/urls.py
from django.contrib import admin
from django.urls import path,include
from myblog.urls import urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('',include('myblog.urls'))
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

myblog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    
    def __str__(self):
        return "{} - {}".format(str(self.id),self.title)

myblog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from myblog.models import Post
# Create your views here.

contex_index = {"titel":"This is dictionary from view.py"}
def view_index(request):
    return render(request,"index.html",contex_index)


contex_about = {"titel":"This about view"}
def view_about(request):
    
    return render(request,"about.html",contex_about)


def view_test(request):
    post = Post.objects.all()
    context = {'post': post}
    return render(request,'test.html',context)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<p>{{titel}}</p>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>This is home</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <h1>Header</h1>
    <a href="{% url 'myblog:index' %}">Home</a>
    <br>
    <a href="{% url 'myblog:about' %}">about</a>
    <br>
    
{% block content %}

{% endblock %}
<h3>This is footer</h3>
</body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
</head>
<body>
    {{post}}
    {% for i in post %}
    <p>{{i}}</p>
    {% endfor %}


    
</body>
</html>